---
# handlers file for ansible-role-proxmox-create-lxc/

# Repintiendo ping cada 3s hasta que el el contenedor arranque
# Repeating ping every 3 seconds until the container starts
- name: pve_lxc wait for connection
  ansible.builtin.wait_for_connection:
    delay: 3
    sleep: 3
    timeout: "{{ pve_lxc_wait_for_connection_timeout | default(60) }}"
  remote_user: "{{ pve_lxc_wait_for_connection_remote_user | default('root') }}"
  when:
    - pve_lxc_net_interfaces is defined
    - pve_lxc_net_interfaces | length > 0
    - pve_lxc_ip_address is defined


...
