---
# Create Proxmox groups using cli tools

- name: Check if {{ current_pve_groupname }} group exists in Proxmox cluster
  command: pveum groupmod "{{ current_pve_groupname }}"
  register: mod_adminsys
  ignore_errors: yes

- name: Create {{ current_pve_groupname }} Proxmox group
  command: pveum groupadd "{{ current_pve_groupname }}" -comment "{{ current_pve_group.comment | default ( omit ) }}"
  when: mod_adminsys.rc != 0

- name: Add user members to {{ current_pve_groupname }} Proxmox group
  command: pveum usermod "{{ pve_group_member }}"@pam -group "{{ current_pve_groupname }}" --append yes
  ignore_errors: yes
  loop: "{{ current_pve_group.members }}"
  loop_control:
    loop_var: pve_group_member

...
