---
# Configuración post-clonación: actualizar los recursos de la máquina virtual

- name: "Post-clone configuration: update virtual machine resources"
  block:
    - name: Post-clone configuration  | password
      community.general.proxmox_kvm:
        api_password: "{{ pve_api_password | default(omit) }}"
      when:
        - is_password_setup
        - not is_token_setup
      register: pve_kvm_virtual_password_created

    - name: Post-clone configuration | Token
      community.general.proxmox_kvm:
        api_token_id: "{{ pve_api_token_id | default(omit) }}"
        api_token_secret: "{{ pve_api_token_secret | default(omit) }}"
      when:
        - is_token_setup
        - not is_password_setup
      register: pve_kvm_virtual_token_created

  delegate_to: "{{ pve_api_host }}"
  module_defaults:
    community.general.proxmox_kvm:
      update: "{{ pve_kvm_update | default('yes') }}"
      node: "{{ pve_node }}"
      api_host: "{{ pve_api_host }}"
      api_user: "{{ pve_api_user | default(omit) }}"
      api_password: "{{ pve_api_password | default(omit) }}"
      proxmox_default_behavior: "{{ pve_kvm_proxmox_default_behavior | default('compatibility') }}"
      validate_certs: "{{ pve_kvm_validate_certs | default(omit) }}"
      name: "{{ pve_hostname }}"
      vmid: "{{ pve_kvm_inferred_vmid | default(omit) }}"
      timeout: "{{ pve_kvm_timeout | default(omit) }}"
      description: "{{ pve_kvm_description | default(omit) }}"
      kvm: "{{ pve_kvm_hardware_virtualization | default(omit) }}"
      ostype: "{{ pve_kvm_ostype | default(omit) }}"
      sockets: "{{ pve_kvm_sockets | default(omit) }}"
      cores: "{{ pve_kvm_cores | default(omit) }}"
      cpu: "{{ pve_kvm_cpu | default(omit) }}"
      cpuunits: "{{ pve_kvm_cpuunits | default(omit) }}"
      cpulimit: "{{ pve_kvm_cpulimit | default(omit) }}"
      memory: "{{ pve_kvm_memory | default(omit) }}"
      balloon: "{{ pve_kvm_balloon | default(omit) }}"
      vga: "{{ pve_kvm_vga | default(omit) }}"
      acpi: "{{ pve_kvm_acpi | default(omit) }}"
      agent: "{{ pve_kvm_agent | default(omit) }}"
      args: "{{ pve_kvm_args | default(omit) }}"
      autostart: "{{ pve_kvm_autostart | default(omit) }}"
      bios: "{{ pve_kvm_bios | default(omit) }}"
      boot: "{{ pve_kvm_boot | default(omit) }}"
      bootdisk: "{{ pve_kvm_bootdisk | default(omit) }}"
      citype: "{{ pve_kvm_citype | default(omit) }}"
      cicustom: "{{ pve_kvm_cicustom | default(omit) }}"
      ciuser: "{{ pve_kvm_ciuser | default(omit) }}"
      cipassword: "{{ pve_kvm_cipassword | default(omit) }}"
      sshkeys: "{{ pve_kvm_sshkeys | default(omit) }}"
      ipconfig: "{{ pve_kvm_ipconfig | default(omit) }}"
      nameservers: "{{ pve_kvm_nameservers | default(omit) }}"
      searchdomains: "{{ pve_kvm_searchdomains | default(omit) }}"
      delete: "{{ pve_kvm_delete | default(omit) }}"
      digest: "{{ pve_kvm_digest | default(omit) }}"
      force: "{{ pve_kvm_force | default(omit) }}"
      freeze: "{{ pve_kvm_freeze | default(omit) }}"
      hostpci: "{{ pve_kvm_hostpci | default(omit) }}"
      hotplug: "{{ pve_kvm_hotplug | default(omit) }}"
      hugepages: "{{ pve_kvm_hugepages | default(omit) }}"
      keyboard: "{{ pve_kvm_keyboard | default(omit) }}"
      localtime: "{{ pve_kvm_localtime | default(omit) }}"
      lock: "{{ pve_kvm_lock | default(omit) }}"
      machine: "{{ pve_kvm_machine | default(omit) }}"
      migrate_downtime: "{{ pve_kvm_migrate_downtime | default(omit) }}"
      migrate_speed: "{{ pve_kvm_migrate_speed | default(omit) }}"
      numa: "{{ pve_kvm_numa | default(omit) }}"
      numa_enabled: "{{ pve_kvm_numa_enabled | default(omit) }}"
      onboot: "{{ pve_onboot | default(omit) }}"
      parallel: "{{ pve_kvm_parallel | default(omit) }}"
      pool: "{{ pve_kvm_pool | default(omit) }}"
      protection: "{{ pve_kvm_protection | default(omit) }}"
      reboot: "{{ pve_kvm_reboot | default(omit) }}"
      revert: "{{ pve_kvm_revert | default(omit) }}"
      scsihw: "{{ pve_kvm_scsihw | default(omit) }}"
      serial: "{{ pve_kvm_serial | default(omit) }}"
      shares: "{{ pve_kvm_shares | default(omit) }}"
      skiplock: "{{ pve_kvm_skiplock | default(omit) }}"
      smbios: "{{ pve_kvm_smbios | default(omit) }}"
      startdate: "{{ pve_kvm_startdate | default(omit) }}"
      startup: "{{ pve_kvm_startup | default(omit) }}"
      # state: "{{ pve_kvm_state | default(omit) }}"
      tablet: "{{ pve_kvm_tablet | default(omit) }}"
      tags: "{{ pve_kvm_tags | default(omit) }}"
      tdf: "{{ pve_kvm_tdf | default(omit) }}"
      vcpus: "{{ pve_kvm_vcpus | default(omit) }}"
      watchdog: "{{ pve_kvm_watchdog | default(omit) }}"

# Configuración post-clonación: expandir los discos de la máquina virtual
- name: "Post-clone configuration: grow up virtual machine disks"
  ansible.builtin.command: "qm resize {{ pve_kvm_inferred_vmid }} {{ item.disk }} +{{ item.increment }}"
  delegate_to: "{{ pve_api_host }}"
  loop: "{{ pve_kvm_clone_grow_disks }}"
  when:
    - pve_kvm_clone_grow_disks is defined
